import type { MutationCtx } from "../_generated/server"

export type CityKey = "bucaramanga" | "bogota"

export type DeliveryAreaTemplateSeed = {
  cityKey: CityKey
  cityName: string
  zoneKey: string
  zoneName: string
  polygon: Array<{ lat: number; lng: number }>
  defaultDeliveryFee: number
  defaultEstimatedDeliveryTime: string
  defaultMinimumOrder: number
  isActive: boolean
  displayOrder: number
}

export const DELIVERY_AREA_TEMPLATE_SEEDS: DeliveryAreaTemplateSeed[] = [
  // ─── BUCARAMANGA: NORTH SECTOR ───────────────────────────────────────
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-norte-kennedy",
    zoneName: "Norte / Kennedy",
    polygon: [
      { lat: 7.165, lng: -73.14 },
      { lat: 7.165, lng: -73.121 },
      { lat: 7.15, lng: -73.121 },
      { lat: 7.15, lng: -73.14 },
    ],
    defaultDeliveryFee: 7000,
    defaultEstimatedDeliveryTime: "40-55 min",
    defaultMinimumOrder: 25000,
    isActive: true,
    displayOrder: 1,
  },
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-nororiental",
    zoneName: "Nororiental / Transición",
    polygon: [
      { lat: 7.165, lng: -73.121 },
      { lat: 7.165, lng: -73.09 },
      { lat: 7.15, lng: -73.09 },
      { lat: 7.15, lng: -73.121 },
    ],
    defaultDeliveryFee: 7500,
    defaultEstimatedDeliveryTime: "45-60 min",
    defaultMinimumOrder: 27000,
    isActive: true,
    displayOrder: 2,
  },
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-san-francisco",
    zoneName: "San Francisco / Universidad",
    polygon: [
      { lat: 7.15, lng: -73.14 },
      { lat: 7.15, lng: -73.121 },
      { lat: 7.138, lng: -73.121 },
      { lat: 7.138, lng: -73.14 },
    ],
    defaultDeliveryFee: 6000,
    defaultEstimatedDeliveryTime: "35-50 min",
    defaultMinimumOrder: 22000,
    isActive: true,
    displayOrder: 3,
  },
  // ─── BUCARAMANGA: CENTRAL-WEST SECTOR ────────────────────────────────
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-occidental",
    zoneName: "Occidental / Zona Industrial",
    polygon: [
      { lat: 7.138, lng: -73.14 },
      { lat: 7.138, lng: -73.127 },
      { lat: 7.127, lng: -73.127 },
      { lat: 7.127, lng: -73.14 },
    ],
    defaultDeliveryFee: 6000,
    defaultEstimatedDeliveryTime: "35-50 min",
    defaultMinimumOrder: 22000,
    isActive: true,
    displayOrder: 4,
  },
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-garcia-rovira",
    zoneName: "García Rovira / Campohermoso",
    polygon: [
      { lat: 7.127, lng: -73.14 },
      { lat: 7.127, lng: -73.127 },
      { lat: 7.12, lng: -73.127 },
      { lat: 7.12, lng: -73.14 },
    ],
    defaultDeliveryFee: 5500,
    defaultEstimatedDeliveryTime: "30-45 min",
    defaultMinimumOrder: 20000,
    isActive: true,
    displayOrder: 5,
  },
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-sur-occidente",
    zoneName: "Sur Occidente / San Gerardo",
    polygon: [
      { lat: 7.12, lng: -73.14 },
      { lat: 7.12, lng: -73.127 },
      { lat: 7.11, lng: -73.127 },
      { lat: 7.11, lng: -73.14 },
    ],
    defaultDeliveryFee: 6000,
    defaultEstimatedDeliveryTime: "35-50 min",
    defaultMinimumOrder: 22000,
    isActive: true,
    displayOrder: 6,
  },
  // ─── BUCARAMANGA: CENTRO & HISTORIC ──────────────────────────────────
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-centro",
    zoneName: "Centro Histórico",
    polygon: [
      { lat: 7.127, lng: -73.127 },
      { lat: 7.127, lng: -73.11 },
      { lat: 7.12, lng: -73.11 },
      { lat: 7.12, lng: -73.127 },
    ],
    defaultDeliveryFee: 4000,
    defaultEstimatedDeliveryTime: "20-35 min",
    defaultMinimumOrder: 18000,
    isActive: true,
    displayOrder: 7,
  },
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-concordia",
    zoneName: "La Concordia",
    polygon: [
      { lat: 7.12, lng: -73.127 },
      { lat: 7.12, lng: -73.11 },
      { lat: 7.11, lng: -73.11 },
      { lat: 7.11, lng: -73.127 },
    ],
    defaultDeliveryFee: 4500,
    defaultEstimatedDeliveryTime: "25-40 min",
    defaultMinimumOrder: 18000,
    isActive: true,
    displayOrder: 8,
  },
  // ─── BUCARAMANGA: EAST-CENTRAL SECTOR ────────────────────────────────
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-oriental",
    zoneName: "Oriental / San Alonso",
    polygon: [
      { lat: 7.138, lng: -73.121 },
      { lat: 7.138, lng: -73.11 },
      { lat: 7.127, lng: -73.11 },
      { lat: 7.127, lng: -73.121 },
    ],
    defaultDeliveryFee: 4500,
    defaultEstimatedDeliveryTime: "25-40 min",
    defaultMinimumOrder: 20000,
    isActive: true,
    displayOrder: 9,
  },
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-cabecera-norte",
    zoneName: "Cabecera del Llano Norte",
    polygon: [
      { lat: 7.127, lng: -73.11 },
      { lat: 7.127, lng: -73.09 },
      { lat: 7.12, lng: -73.09 },
      { lat: 7.12, lng: -73.11 },
    ],
    defaultDeliveryFee: 4000,
    defaultEstimatedDeliveryTime: "20-35 min",
    defaultMinimumOrder: 18000,
    isActive: true,
    displayOrder: 10,
  },
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-cabecera-sur",
    zoneName: "Cabecera del Llano Sur / La Floresta",
    polygon: [
      { lat: 7.12, lng: -73.11 },
      { lat: 7.12, lng: -73.09 },
      { lat: 7.11, lng: -73.09 },
      { lat: 7.11, lng: -73.11 },
    ],
    defaultDeliveryFee: 4500,
    defaultEstimatedDeliveryTime: "25-40 min",
    defaultMinimumOrder: 18000,
    isActive: true,
    displayOrder: 11,
  },
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-morrorico",
    zoneName: "Morrorico / Oriental",
    polygon: [
      { lat: 7.15, lng: -73.11 },
      { lat: 7.15, lng: -73.09 },
      { lat: 7.138, lng: -73.09 },
      { lat: 7.138, lng: -73.11 },
    ],
    defaultDeliveryFee: 7000,
    defaultEstimatedDeliveryTime: "40-55 min",
    defaultMinimumOrder: 25000,
    isActive: true,
    displayOrder: 12,
  },
  // ─── BUCARAMANGA: SOUTH-CENTRAL SECTOR ───────────────────────────────
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-pedregosa",
    zoneName: "La Pedregosa",
    polygon: [
      { lat: 7.11, lng: -73.127 },
      { lat: 7.11, lng: -73.11 },
      { lat: 7.1, lng: -73.11 },
      { lat: 7.1, lng: -73.127 },
    ],
    defaultDeliveryFee: 5000,
    defaultEstimatedDeliveryTime: "30-45 min",
    defaultMinimumOrder: 20000,
    isActive: true,
    displayOrder: 13,
  },
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-provenza",
    zoneName: "Provenza",
    polygon: [
      { lat: 7.11, lng: -73.11 },
      { lat: 7.11, lng: -73.09 },
      { lat: 7.1, lng: -73.09 },
      { lat: 7.1, lng: -73.11 },
    ],
    defaultDeliveryFee: 5000,
    defaultEstimatedDeliveryTime: "30-45 min",
    defaultMinimumOrder: 20000,
    isActive: true,
    displayOrder: 14,
  },
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-lagos-cacique",
    zoneName: "Lagos del Cacique",
    polygon: [
      { lat: 7.12, lng: -73.09 },
      { lat: 7.12, lng: -73.065 },
      { lat: 7.11, lng: -73.065 },
      { lat: 7.11, lng: -73.09 },
    ],
    defaultDeliveryFee: 5500,
    defaultEstimatedDeliveryTime: "30-45 min",
    defaultMinimumOrder: 22000,
    isActive: true,
    displayOrder: 15,
  },
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-mutis",
    zoneName: "Mutis / Balconcitos",
    polygon: [
      { lat: 7.11, lng: -73.09 },
      { lat: 7.11, lng: -73.065 },
      { lat: 7.1, lng: -73.065 },
      { lat: 7.1, lng: -73.09 },
    ],
    defaultDeliveryFee: 6000,
    defaultEstimatedDeliveryTime: "35-50 min",
    defaultMinimumOrder: 22000,
    isActive: true,
    displayOrder: 16,
  },
  // ─── BUCARAMANGA: SOUTH SECTOR ───────────────────────────────────────
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-ciudadela",
    zoneName: "Ciudadela Real de Minas",
    polygon: [
      { lat: 7.11, lng: -73.14 },
      { lat: 7.11, lng: -73.127 },
      { lat: 7.1, lng: -73.127 },
      { lat: 7.1, lng: -73.14 },
    ],
    defaultDeliveryFee: 6500,
    defaultEstimatedDeliveryTime: "35-50 min",
    defaultMinimumOrder: 22000,
    isActive: true,
    displayOrder: 17,
  },
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-sur",
    zoneName: "Sur / Toledo Plata",
    polygon: [
      { lat: 7.1, lng: -73.14 },
      { lat: 7.1, lng: -73.11 },
      { lat: 7.09, lng: -73.11 },
      { lat: 7.09, lng: -73.14 },
    ],
    defaultDeliveryFee: 7000,
    defaultEstimatedDeliveryTime: "40-55 min",
    defaultMinimumOrder: 25000,
    isActive: true,
    displayOrder: 18,
  },
  // ─── BUCARAMANGA: METROPOLITAN EXTENSIONS ────────────────────────────
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-florida-norte",
    zoneName: "Floridablanca Norte / Cañaveral",
    polygon: [
      { lat: 7.09, lng: -73.14 },
      { lat: 7.09, lng: -73.09 },
      { lat: 7.075, lng: -73.09 },
      { lat: 7.075, lng: -73.14 },
    ],
    defaultDeliveryFee: 7000,
    defaultEstimatedDeliveryTime: "40-55 min",
    defaultMinimumOrder: 25000,
    isActive: true,
    displayOrder: 19,
  },
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-florida-centro",
    zoneName: "Floridablanca Centro",
    polygon: [
      { lat: 7.075, lng: -73.12 },
      { lat: 7.075, lng: -73.065 },
      { lat: 7.062, lng: -73.065 },
      { lat: 7.062, lng: -73.12 },
    ],
    defaultDeliveryFee: 7500,
    defaultEstimatedDeliveryTime: "45-60 min",
    defaultMinimumOrder: 27000,
    isActive: true,
    displayOrder: 20,
  },
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-florida-sur",
    zoneName: "Floridablanca Sur / La Cumbre",
    polygon: [
      { lat: 7.062, lng: -73.12 },
      { lat: 7.062, lng: -73.065 },
      { lat: 7.04, lng: -73.065 },
      { lat: 7.04, lng: -73.12 },
    ],
    defaultDeliveryFee: 8000,
    defaultEstimatedDeliveryTime: "50-70 min",
    defaultMinimumOrder: 30000,
    isActive: true,
    displayOrder: 21,
  },
  {
    cityKey: "bucaramanga",
    cityName: "Bucaramanga",
    zoneKey: "bga-giron",
    zoneName: "Girón / El Poblado",
    polygon: [
      { lat: 7.09, lng: -73.175 },
      { lat: 7.09, lng: -73.14 },
      { lat: 7.062, lng: -73.14 },
      { lat: 7.062, lng: -73.175 },
    ],
    defaultDeliveryFee: 8000,
    defaultEstimatedDeliveryTime: "50-70 min",
    defaultMinimumOrder: 30000,
    isActive: true,
    displayOrder: 22,
  },
  // ─── BOGOTÁ: NORTH SECTOR ─────────────────────────────────────────
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-usaquen-norte",
    zoneName: "Usaquén Norte",
    polygon: [
      { lat: 4.84, lng: -74.065 },
      { lat: 4.84, lng: -74.01 },
      { lat: 4.75, lng: -74.01 },
      { lat: 4.75, lng: -74.065 },
    ],
    defaultDeliveryFee: 8000,
    defaultEstimatedDeliveryTime: "45-60 min",
    defaultMinimumOrder: 30000,
    isActive: true,
    displayOrder: 1,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-usaquen-sur",
    zoneName: "Usaquén Sur",
    polygon: [
      { lat: 4.75, lng: -74.065 },
      { lat: 4.75, lng: -74.01 },
      { lat: 4.72, lng: -74.01 },
      { lat: 4.72, lng: -74.065 },
    ],
    defaultDeliveryFee: 6500,
    defaultEstimatedDeliveryTime: "35-50 min",
    defaultMinimumOrder: 25000,
    isActive: true,
    displayOrder: 2,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-suba-norte",
    zoneName: "Suba Norte",
    polygon: [
      { lat: 4.84, lng: -74.13 },
      { lat: 4.84, lng: -74.065 },
      { lat: 4.75, lng: -74.065 },
      { lat: 4.75, lng: -74.13 },
    ],
    defaultDeliveryFee: 8500,
    defaultEstimatedDeliveryTime: "50-65 min",
    defaultMinimumOrder: 30000,
    isActive: true,
    displayOrder: 3,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-suba-sur",
    zoneName: "Suba Sur",
    polygon: [
      { lat: 4.75, lng: -74.13 },
      { lat: 4.75, lng: -74.065 },
      { lat: 4.72, lng: -74.065 },
      { lat: 4.72, lng: -74.13 },
    ],
    defaultDeliveryFee: 7500,
    defaultEstimatedDeliveryTime: "40-55 min",
    defaultMinimumOrder: 27000,
    isActive: true,
    displayOrder: 4,
  },
  // ─── BOGOTÁ: NORTH-CENTRAL SECTOR ──────────────────────────────────
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-chapinero-norte",
    zoneName: "Chapinero Norte",
    polygon: [
      { lat: 4.72, lng: -74.065 },
      { lat: 4.72, lng: -74.01 },
      { lat: 4.695, lng: -74.01 },
      { lat: 4.695, lng: -74.065 },
    ],
    defaultDeliveryFee: 5500,
    defaultEstimatedDeliveryTime: "25-40 min",
    defaultMinimumOrder: 22000,
    isActive: true,
    displayOrder: 5,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-chapinero-sur",
    zoneName: "Chapinero Sur",
    polygon: [
      { lat: 4.695, lng: -74.065 },
      { lat: 4.695, lng: -74.01 },
      { lat: 4.67, lng: -74.01 },
      { lat: 4.67, lng: -74.065 },
    ],
    defaultDeliveryFee: 5000,
    defaultEstimatedDeliveryTime: "25-40 min",
    defaultMinimumOrder: 20000,
    isActive: true,
    displayOrder: 6,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-barrios-unidos",
    zoneName: "Barrios Unidos",
    polygon: [
      { lat: 4.72, lng: -74.085 },
      { lat: 4.72, lng: -74.065 },
      { lat: 4.67, lng: -74.065 },
      { lat: 4.67, lng: -74.085 },
    ],
    defaultDeliveryFee: 5500,
    defaultEstimatedDeliveryTime: "30-45 min",
    defaultMinimumOrder: 22000,
    isActive: true,
    displayOrder: 7,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-engativa-norte",
    zoneName: "Engativá Norte",
    polygon: [
      { lat: 4.75, lng: -74.155 },
      { lat: 4.75, lng: -74.13 },
      { lat: 4.72, lng: -74.13 },
      { lat: 4.72, lng: -74.155 },
    ],
    defaultDeliveryFee: 8000,
    defaultEstimatedDeliveryTime: "45-60 min",
    defaultMinimumOrder: 28000,
    isActive: true,
    displayOrder: 8,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-engativa-sur",
    zoneName: "Engativá Sur",
    polygon: [
      { lat: 4.72, lng: -74.155 },
      { lat: 4.72, lng: -74.085 },
      { lat: 4.695, lng: -74.085 },
      { lat: 4.695, lng: -74.155 },
    ],
    defaultDeliveryFee: 7000,
    defaultEstimatedDeliveryTime: "40-55 min",
    defaultMinimumOrder: 25000,
    isActive: true,
    displayOrder: 9,
  },
  // ─── BOGOTÁ: CENTRAL SECTOR ────────────────────────────────────────
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-teusaquillo",
    zoneName: "Teusaquillo",
    polygon: [
      { lat: 4.67, lng: -74.11 },
      { lat: 4.67, lng: -74.065 },
      { lat: 4.635, lng: -74.065 },
      { lat: 4.635, lng: -74.11 },
    ],
    defaultDeliveryFee: 5000,
    defaultEstimatedDeliveryTime: "25-40 min",
    defaultMinimumOrder: 20000,
    isActive: true,
    displayOrder: 10,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-fontibon-norte",
    zoneName: "Fontibón Norte",
    polygon: [
      { lat: 4.695, lng: -74.22 },
      { lat: 4.695, lng: -74.155 },
      { lat: 4.67, lng: -74.155 },
      { lat: 4.67, lng: -74.22 },
    ],
    defaultDeliveryFee: 8500,
    defaultEstimatedDeliveryTime: "50-65 min",
    defaultMinimumOrder: 30000,
    isActive: true,
    displayOrder: 11,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-fontibon-sur",
    zoneName: "Fontibón Sur",
    polygon: [
      { lat: 4.67, lng: -74.22 },
      { lat: 4.67, lng: -74.11 },
      { lat: 4.635, lng: -74.11 },
      { lat: 4.635, lng: -74.22 },
    ],
    defaultDeliveryFee: 8000,
    defaultEstimatedDeliveryTime: "45-60 min",
    defaultMinimumOrder: 28000,
    isActive: true,
    displayOrder: 12,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-santa-fe",
    zoneName: "Santa Fe / Centro",
    polygon: [
      { lat: 4.635, lng: -74.065 },
      { lat: 4.635, lng: -74.01 },
      { lat: 4.61, lng: -74.01 },
      { lat: 4.61, lng: -74.065 },
    ],
    defaultDeliveryFee: 5500,
    defaultEstimatedDeliveryTime: "30-45 min",
    defaultMinimumOrder: 22000,
    isActive: true,
    displayOrder: 13,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-candelaria",
    zoneName: "La Candelaria",
    polygon: [
      { lat: 4.61, lng: -74.065 },
      { lat: 4.61, lng: -74.03 },
      { lat: 4.595, lng: -74.03 },
      { lat: 4.595, lng: -74.065 },
    ],
    defaultDeliveryFee: 6000,
    defaultEstimatedDeliveryTime: "30-45 min",
    defaultMinimumOrder: 22000,
    isActive: true,
    displayOrder: 14,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-martires",
    zoneName: "Los Mártires",
    polygon: [
      { lat: 4.635, lng: -74.11 },
      { lat: 4.635, lng: -74.065 },
      { lat: 4.61, lng: -74.065 },
      { lat: 4.61, lng: -74.11 },
    ],
    defaultDeliveryFee: 6000,
    defaultEstimatedDeliveryTime: "30-45 min",
    defaultMinimumOrder: 22000,
    isActive: true,
    displayOrder: 15,
  },
  // ─── BOGOTÁ: WEST-CENTRAL SECTOR ───────────────────────────────────
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-puente-aranda",
    zoneName: "Puente Aranda",
    polygon: [
      { lat: 4.61, lng: -74.13 },
      { lat: 4.61, lng: -74.065 },
      { lat: 4.595, lng: -74.065 },
      { lat: 4.595, lng: -74.13 },
    ],
    defaultDeliveryFee: 6500,
    defaultEstimatedDeliveryTime: "35-50 min",
    defaultMinimumOrder: 23000,
    isActive: true,
    displayOrder: 16,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-kennedy-norte",
    zoneName: "Kennedy Norte",
    polygon: [
      { lat: 4.635, lng: -74.22 },
      { lat: 4.635, lng: -74.11 },
      { lat: 4.61, lng: -74.11 },
      { lat: 4.61, lng: -74.22 },
    ],
    defaultDeliveryFee: 7500,
    defaultEstimatedDeliveryTime: "40-55 min",
    defaultMinimumOrder: 27000,
    isActive: true,
    displayOrder: 17,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-kennedy-sur",
    zoneName: "Kennedy Sur",
    polygon: [
      { lat: 4.61, lng: -74.22 },
      { lat: 4.61, lng: -74.13 },
      { lat: 4.595, lng: -74.13 },
      { lat: 4.595, lng: -74.22 },
    ],
    defaultDeliveryFee: 8000,
    defaultEstimatedDeliveryTime: "45-60 min",
    defaultMinimumOrder: 28000,
    isActive: true,
    displayOrder: 18,
  },
  // ─── BOGOTÁ: SOUTH-CENTRAL SECTOR ──────────────────────────────────
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-antonio-narino",
    zoneName: "Antonio Nariño",
    polygon: [
      { lat: 4.595, lng: -74.065 },
      { lat: 4.595, lng: -74.03 },
      { lat: 4.58, lng: -74.03 },
      { lat: 4.58, lng: -74.065 },
    ],
    defaultDeliveryFee: 6500,
    defaultEstimatedDeliveryTime: "35-50 min",
    defaultMinimumOrder: 23000,
    isActive: true,
    displayOrder: 19,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-rafael-uribe",
    zoneName: "Rafael Uribe Uribe",
    polygon: [
      { lat: 4.595, lng: -74.13 },
      { lat: 4.595, lng: -74.065 },
      { lat: 4.56, lng: -74.065 },
      { lat: 4.56, lng: -74.13 },
    ],
    defaultDeliveryFee: 7000,
    defaultEstimatedDeliveryTime: "40-55 min",
    defaultMinimumOrder: 25000,
    isActive: true,
    displayOrder: 20,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-san-cristobal",
    zoneName: "San Cristóbal",
    polygon: [
      { lat: 4.58, lng: -74.065 },
      { lat: 4.58, lng: -74.01 },
      { lat: 4.56, lng: -74.01 },
      { lat: 4.56, lng: -74.065 },
    ],
    defaultDeliveryFee: 7500,
    defaultEstimatedDeliveryTime: "40-55 min",
    defaultMinimumOrder: 27000,
    isActive: true,
    displayOrder: 21,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-tunjuelito",
    zoneName: "Tunjuelito",
    polygon: [
      { lat: 4.595, lng: -74.155 },
      { lat: 4.595, lng: -74.13 },
      { lat: 4.56, lng: -74.13 },
      { lat: 4.56, lng: -74.155 },
    ],
    defaultDeliveryFee: 7500,
    defaultEstimatedDeliveryTime: "45-60 min",
    defaultMinimumOrder: 27000,
    isActive: true,
    displayOrder: 22,
  },
  // ─── BOGOTÁ: SOUTHWEST SECTOR ──────────────────────────────────────
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-bosa-norte",
    zoneName: "Bosa Norte",
    polygon: [
      { lat: 4.61, lng: -74.22 },
      { lat: 4.61, lng: -74.155 },
      { lat: 4.58, lng: -74.155 },
      { lat: 4.58, lng: -74.22 },
    ],
    defaultDeliveryFee: 8500,
    defaultEstimatedDeliveryTime: "50-65 min",
    defaultMinimumOrder: 30000,
    isActive: true,
    displayOrder: 23,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-bosa-sur",
    zoneName: "Bosa Sur",
    polygon: [
      { lat: 4.58, lng: -74.22 },
      { lat: 4.58, lng: -74.155 },
      { lat: 4.56, lng: -74.155 },
      { lat: 4.56, lng: -74.22 },
    ],
    defaultDeliveryFee: 9000,
    defaultEstimatedDeliveryTime: "55-70 min",
    defaultMinimumOrder: 32000,
    isActive: true,
    displayOrder: 24,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-ciudad-bolivar-norte",
    zoneName: "Ciudad Bolívar Norte",
    polygon: [
      { lat: 4.56, lng: -74.185 },
      { lat: 4.56, lng: -74.13 },
      { lat: 4.52, lng: -74.13 },
      { lat: 4.52, lng: -74.185 },
    ],
    defaultDeliveryFee: 8500,
    defaultEstimatedDeliveryTime: "50-65 min",
    defaultMinimumOrder: 30000,
    isActive: true,
    displayOrder: 25,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-ciudad-bolivar-sur",
    zoneName: "Ciudad Bolívar Sur",
    polygon: [
      { lat: 4.52, lng: -74.185 },
      { lat: 4.52, lng: -74.13 },
      { lat: 4.48, lng: -74.13 },
      { lat: 4.48, lng: -74.185 },
    ],
    defaultDeliveryFee: 9000,
    defaultEstimatedDeliveryTime: "55-75 min",
    defaultMinimumOrder: 35000,
    isActive: true,
    displayOrder: 26,
  },
  // ─── BOGOTÁ: FAR SOUTH SECTOR ──────────────────────────────────────
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-usme-norte",
    zoneName: "Usme Norte",
    polygon: [
      { lat: 4.56, lng: -74.13 },
      { lat: 4.56, lng: -74.065 },
      { lat: 4.52, lng: -74.065 },
      { lat: 4.52, lng: -74.13 },
    ],
    defaultDeliveryFee: 8500,
    defaultEstimatedDeliveryTime: "50-65 min",
    defaultMinimumOrder: 30000,
    isActive: true,
    displayOrder: 27,
  },
  {
    cityKey: "bogota",
    cityName: "Bogotá",
    zoneKey: "bogota-usme-sur",
    zoneName: "Usme Sur",
    polygon: [
      { lat: 4.52, lng: -74.13 },
      { lat: 4.52, lng: -74.065 },
      { lat: 4.45, lng: -74.065 },
      { lat: 4.45, lng: -74.13 },
    ],
    defaultDeliveryFee: 9000,
    defaultEstimatedDeliveryTime: "55-75 min",
    defaultMinimumOrder: 35000,
    isActive: true,
    displayOrder: 28,
  },
]

export async function seedDeliveryAreaTemplatesIfEmpty(ctx: MutationCtx) {
  const existingTemplates = await ctx.db
    .query("deliveryAreaTemplates")
    .collect()

  const existingKeys = new Set(
    existingTemplates.map((t) => `${t.cityKey}:${t.zoneKey}`)
  )

  for (const template of DELIVERY_AREA_TEMPLATE_SEEDS) {
    const key = `${template.cityKey}:${template.zoneKey}`
    if (!existingKeys.has(key)) {
      await ctx.db.insert("deliveryAreaTemplates", template)
    }
  }
}
